WIP - VB-1748 move prisoner profile page requests to orchestration service
ministryofjustice/hmpps-manage-prison-visits-orchestration pull request #7
Opened 2023-02-20 08:53 UTC by dhirajshettymoj

Add prisoner profile page endpoint to orchestration service

2023-02-20 08:53 UTC, dhirajshettymoj commented
Draft PR request for review. Some work is pending on making the calls to endpoints asynchronously.

2023-02-22 09:11 UTC, AledWEvans requested changes
The code is good code a few comments, The thing is I'm noticing names of properties that are different for the same things offenderNo, prisonerId, prisonerNumber, convention dictates these should be all name the same thing in our system,.. but what we are doing is importing the names from the third party systems and therefor breaking encapsulation rules and allowing legacy inconstancies in our system.

2023-02-22 15:28 UTC, dhirajshettymoj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/whereabouts/ScheduledEventDto.kt
> +  val eventDate: @NotNull LocalDate? = null,
I have updated it based on the Schema here - https://whereabouts-api-dev.service.justice.gov.uk/swagger-ui/index.html to make only bookingId a NotNull field. Currently the WhereAbouts API call is not integrated. When we integrate the WhereAbouts API call we will drop the fields not needed and will revisit this DTO then.

2023-02-22 16:05 UTC, dhirajshettymoj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/PrisonerProfileDto.kt
> +  val offenderNo: String,
Updated to prisonerId in almost all instances except where the Dto is for an external client response.

2023-02-22 16:36 UTC, AledWEvans approved these changes
LGTM

2023-02-22 17:10 UTC, merged